# Generated by Django 4.2.4 on 2023-08-23 16:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Admins',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('surname', models.CharField(max_length=128)),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('password', models.CharField(max_length=1024)),
                ('job_title', models.CharField(max_length=128)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users')),
                ('active', models.BooleanField(default=False)),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('up_on', models.DateTimeField(auto_now=True, null=True)),
                ('cr_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='way_merch_cr_by', to=settings.AUTH_USER_MODEL)),
                ('up_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='way_merch_up_by', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admin',
                'verbose_name_plural': 'Admins',
            },
        ),
    ]
