# Generated by Django 4.1 on 2023-08-26 09:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admins',
            name='active',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='email',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='name',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='password',
        ),
        migrations.RemoveField(
            model_name='admins',
            name='surname',
        ),
        migrations.AddField(
            model_name='admins',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admins', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='admins',
            name='cr_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_cr_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='admins',
            name='up_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_up_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=32)),
                ('email', models.CharField(blank=True, max_length=128, null=True)),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
