# Generated by Django 4.2.4 on 2023-09-13 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_alter_clients_options_operators'),
        ('goods', '0003_goods_price_for_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('count_of_products', models.IntegerField(default=1)),
                ('region', models.TextField(max_length=32)),
                ('description', models.TextField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(choices=[('1', 'Yangi'), ('2', 'Qabul qilindi'), ('3', 'Yetkazilmoqda'), ('4', 'Keyin'), ('5', 'Oladi'), ('6', "Qayta Qo'ng'iroq"), ('7', 'Arxiv'), ('8', 'Yetqazib berildi')], default=1, max_length=100)),
                ('cr_on', models.DateTimeField(auto_now_add=True)),
                ('up_on', models.DateTimeField(blank=True, null=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='products', to='goods.goods')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='users.clients')),
            ],
        ),
    ]
