# Generated by Django 4.2.4 on 2023-09-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0002_alter_orders_options_alter_orders_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='description',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='region',
            field=models.CharField(default='uz', max_length=32),
        ),
    ]
