# Generated by Django 4.2.4 on 2023-09-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_clients_options_operators'),
        ('claims', '0004_orders_operator_alter_orders_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='admin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admins', to='users.admins'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='orders',
            name='comment',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_name',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='user_phone_number',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='clients', to='users.clients'),
        ),
    ]
