# Generated by Django 4.2.4 on 2023-09-16 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0005_orders_admin_orders_comment_orders_user_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='total_amount',
            field=models.IntegerField(default=0),
        ),
    ]
