# Generated by Django 4.2.4 on 2023-09-17 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_clients_options_operators'),
        ('claims', '0006_orders_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='admins', to='users.admins'),
        ),
    ]
