# Generated by Django 4.1 on 2023-08-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='goods',
            name='currency',
            field=models.CharField(default='UZS', max_length=12),
        ),
    ]
